apiVersion: v1
kind: Service
metadata:
  name: tracker-api-service
spec:
  selector:
    app: tracker-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-api
  labels:
    app: tracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker-api
  template:
    metadata:
      labels:
        app: tracker-api
    spec:
      containers:
        - name: tracker-api
          image: istiyaqmi9/bot-tracker
          ports:
            - containerPort: 8080
