apiVersion: apps/v1
kind: Deployment
metadata:
  name: aamnaz-site
  labels:
    app: aamnaz-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aamnaz-site
  template:
    metadata:
      labels:
        app: aamnaz-site
    spec:
      containers:
        - name: aamnaz-site
          image: istiyaqmi9/aamnaz-site:latest
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: aamnaz-service
spec:
  selector:
    app: aamnaz-site
  ports:
    - protocol: TCP
      port: 8194
      targetPort: 80
  type: LoadBalancer